### ISSUE TITLE
Create the "add new profile" component

### ISSUE THREAD

**Issue by RobbieMcKinstry** [alligrader/gradebook#5]
# Abstract

When the user makes a new profile, they'll need to specify which configurations they'd like to include in their profile. The configures, being very complex, need to be built programmatically.

# Introduction

A "profile" (or "bug profile") consists of a set of static analysis tools and their configuration. A profile represents the specification of what checks will be performed on the user's code at check-in.

Right now, we're going to support two different static analysis tools: FindBugs and Checkstyle. The configuration for each of these two programs is extensive: they each have over a hundred different features we can toggle on or off. As such, we're not going to build the UI manually to reflect the hundreds of components; that would be a waste of deverlopment time. What happens if we want to add a new tool? Do we need to manually build another hundred UI components? 

Instead, we're going to programmatically build the UI components from a specification of the API. The specificatin of the API is written in JSON, and located at `/api/swagger.json`.

Take a look at the JSON to see the structure:
Let's assume you marshall the JSON into a JS object called `Blob`. Looking at the JSON, you'll see the top level object has a field called `defintions`. Indexing into `Blob.defintions` gives you an object with two important fields: `Checkstyle` and `Findbugs`. You'll notice that these two objects have one really important field: `properties`. The `properties` field contains each of the fields that we want to represent in our UI.

Thus, to build our UI, we need to iterate over `Blob.defintions.Findbugs.properties` and `Blob.defintions.Checkstyle.properties`, and build a checkbox for each of the properties. 

Why a checkbox? Well, for now, we're representing each of the checks as a boolean: either we include the check or we don't. Therefore, we have a single checkbox for each of the checks.

# TODO

- [ ] On component mount, make a request to the backend at `/api/swagger.json`.
- [ ] Parse the returned JSON into an object and store it in the state.
- [ ] Read in the Swagger Properties stored in the Redux store as a React prop (i.e. implement `mapPropsToState`)
- [ ] Build a labeled checkbox for each of Swagger properties.
- [ ] When a profile is finally created, call an Action Creator to create an action with all of the data from the checkboxes. The Reducer for this action should send the data back to the backend. The route to the backend is `/api/bug-profile`. There's an autogenerated JS library located in directory `gradebook-api/src/js` and another in `gradebook-api/reduxa` for Redux actions and action creators. These are autogeneated to work closely with the API to hit the right URLs.

# Nota Bene

- I'm using the word **property** in two different ways in the above context. It's unfortunate, but I didn't invent the terminology. React has **properties** (props), which are data passed into React components. Swagger also describes resource types as structural types with properties ( think: a structural type is a Java Class, and a property is an instance variable). When reading the word "property", think about what the context is: either Swagger or React. Sorry for the confusion. 

- I probably have to rename the route from `/api/bug-profile` to `api/bug_profile` because I don't think the Reduxa library code will fair to parse as it currently stands.
